name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Converting dataset to RDF 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
         sudo pip3 install rdflib geopandas shapely pyshp geodatasets geojson_rewind
         mkdir result
         python3 src/rdfconverter.py --input Limes_Coordinates_Kleinkastell.geojson --output result/ --mapping mapping/sampleempty.json
         python3 src/rdfconverter.py --input Limes_Coordinates_Kleinkastell.geojson --output result/ --mapping mapping/limes.json
         cp mapping/limes.json result/
         cp mapping.sampleempty.json result/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: result/