name: GeoRDF Converter

permissions:
  contents: write
 
on:
  workflow_call:
   inputs:
      input:
        required: false
        type: string
        description: "The input file(s) to process"
        default: main
      output:
        required: false
        description: "The output filepath"
        default: None
        type: string
      mapping:
        required: false
        description: "The mapping file to use for conversion"
        default: ""
        type: string
      bibtex:
        required: false
        description: "A bibtex file to link to references"
        default: "" 
        type: string
      sepchar:
        required: false
        type: string
        description: "Separation character for csv input"
        default: ";"
      ghpages:
        required: false
        description: "Indicates whether to create a deployment to a pages branch"
        default: false
        type: boolean
      ghpagesbranch:
        required: false
        description: "The branch to deploy the documentation to"
        default: gh-pages
        type: string
      ghpagesfolder:
        required: false
        description: "The folder which is used for the pages deployment"
        default: /
        type: string
jobs:
    mapping-action:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: '0'
        - name: Checkout tools repo
          id: checkout_tools
          uses: actions/checkout@v3
          continue-on-error: true
          with:
            repository: situx/geordfconverter
            path: geordfconverterscript
        - name: Checkout tools repo fallback
          if: steps.checkout_tools.outcome != 'success'
          uses: actions/checkout@v3
          with:
            repository: situx/geordfconverter
            ref: "main"
            path: geordfconverterscript    
        - name: Mapping File Contents to RDF
          run: |
            sudo pip3 install rdflib geopandas shapely pyshp geodatasets geojson_rewind bibtexparser
            python3 geordfconverterscript/src/rdfconverter.py --input "${{inputs.input}}" --output "${{inputs.output}}" --mapping "${{inputs.mapping}}" --bibtex "${{inputs.bibtex}}" --sepchar "${{inputs.sepchar}}"  
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@releases/v4
          if: ${{ inputs.ghpages }}
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: ${{inputs.ghpagesbranch}}
            FOLDER: ${{inputs.output}}/
            clean: false
            TARGET-FOLDER: ${{inputs.ghpagesfolder}}
